#!/usr/bin/env bash
# The same corpus behind the same policy, one model after another.
#
#   ./gym/run_models.sh
#   ./gym/run_models.sh 3            # three seeds per cell
#
# Only `undefended` and `standard` run here. The question this answers is
# how much the firewall adds on top of whatever the model already refuses,
# and the tiers either side of standard don't bear on it — dropping them
# turns four models from an overnight job into an afternoon.
#
# Writes gym/results/models/<short name>/{approve,deny}/ and prints the
# comparison table.

set -euo pipefail

RUNS="${1:-1}"
CONCURRENCY="${2:-6}"
OUT="gym/results/models"
PY="${PY:-.venv/bin/python}"

if [ -z "${NVIDIA_API_KEY:-}" ]; then
  echo "NVIDIA_API_KEY is not set. Free credits at https://build.nvidia.com." >&2
  exit 2
fi

# Two sizes and two labs. Size varies within nvidia, so the drop between
# those two rows is capability alone; the meta row checks that nothing
# here is an artefact of one lab's training.
#
# z-ai/glm-5.2 is deliberately not in this list. Its numbers are in
# docs/models.md, reconstructed from a run that lost 7.9% of its cells to
# timeouts: it reasons at length every turn, and a run is ten or so
# turns. Rerunning it at a timeout generous enough to avoid the drops
# costs about sixteen minutes a run — nineteen hours for one seed of this
# matrix — so it is not something this script should start on your
# behalf. That is a fact about long-thinking models on a multi-turn
# benchmark rather than a judgement about the model.
MODELS="
ultra-550b|nvidia/nemotron-3-ultra-550b-a55b
lightning-30b|nvidia/nemotron-3.5-lightning-30b-a3b
muse-30b|meta/muse-glimmer-30b
"

echo "$MODELS" | while IFS='|' read -r SHORT MODEL; do
  [ -z "$SHORT" ] && continue
  for BRACKET in approve deny; do
    echo "==> $SHORT ($MODEL) human=$BRACKET"
    $PY -m tripwire_gym --agent nvidia --model "$MODEL" \
      --conditions undefended,standard --runs "$RUNS" \
      --human "$BRACKET" --concurrency "$CONCURRENCY" \
      --out "$OUT/$SHORT/$BRACKET"
  done
done

echo
$PY - <<PYEOF
from pathlib import Path
from tripwire_gym.analysis import load_results, model_comparison

rows = {}
for d in sorted(Path("$OUT").iterdir()):
    results = d / "approve" / "results.jsonl"
    if results.exists():
        rows[d.name] = load_results(results)

report = model_comparison(rows)
print(report)
Path("docs/models.md").write_text(
    "# The same firewall, different models\n\n"
    "Generated by \`./gym/run_models.sh\`.\n\n" + report + "\n"
)
print("\nwrote docs/models.md")
PYEOF
