#!/usr/bin/env bash
# The same corpus behind the same policy, one model after another.
#
#   ./gym/run_models.sh
#   ./gym/run_models.sh 3            # three repetitions per cell
#
# Only `undefended` and `standard` run here. The question this answers is
# how much the firewall adds on top of whatever the model already refuses,
# and the tiers either side of standard don't bear on it — dropping them
# turns four models from an overnight job into an afternoon.
#
# Writes gym/results/models/<short name>/{approve,deny}/ and prints the
# comparison table.

set -euo pipefail

RUNS="${1:-1}"
CONCURRENCY="${2:-6}"
OUT="gym/results/models"
PY="${PY:-.venv/bin/python}"

if [ -z "${NVIDIA_API_KEY:-}" ]; then
  echo "NVIDIA_API_KEY is not set. Free credits at https://build.nvidia.com." >&2
  exit 2
fi

# Three current Nemotron sizes plus a second model family. The third field
# records whether the provider's thinking template should be disabled for
# tool calling.
MODELS="
nano-30b|nvidia/nemotron-3-nano-30b-a3b|disable
super-120b|nvidia/nemotron-3-super-120b-a12b|disable
ultra-550b|nvidia/nemotron-3-ultra-550b-a55b|disable
glm-5.2|z-ai/glm-5.2|keep
"

echo "$MODELS" | while IFS='|' read -r SHORT MODEL THINKING; do
  [ -z "$SHORT" ] && continue
  for BRACKET in approve deny; do
    echo "==> $SHORT ($MODEL) human=$BRACKET"
    if [ "$THINKING" = "disable" ]; then
      $PY -m tripwire_gym --agent nvidia --model "$MODEL" \
        --conditions undefended,standard --runs "$RUNS" \
        --human "$BRACKET" --concurrency "$CONCURRENCY" \
        --prompt-profile plain --temperature 0 --disable-thinking \
        --shuffle-seed 17229 --out "$OUT/$SHORT/$BRACKET"
    else
      $PY -m tripwire_gym --agent nvidia --model "$MODEL" \
        --conditions undefended,standard --runs "$RUNS" \
        --human "$BRACKET" --concurrency "$CONCURRENCY" \
        --prompt-profile plain --temperature 0 --shuffle-seed 17229 \
        --out "$OUT/$SHORT/$BRACKET"
    fi
  done
done

echo
$PY - <<PYEOF
from pathlib import Path
from tripwire_gym.analysis import load_results, model_comparison

rows = {}
for d in sorted(Path("$OUT").iterdir()):
    results = d / "approve" / "results.jsonl"
    if results.exists():
        rows[d.name] = load_results(results)

report = model_comparison(rows)
print(report)
Path("docs/models.md").write_text(
    "# The same firewall, different models\n\n"
    "Generated by \`./gym/run_models.sh\`.\n\n" + report + "\n"
)
print("\nwrote docs/models.md")
PYEOF
