"""Generate leave-one-component-out policies from the policy under test.

Cumulative ablations answer whether a partial stack is sufficient.  They are
order-dependent.  These policies answer the cleaner publication question:
how much does the *full* stack change when exactly one mechanism is removed?
"""

from __future__ import annotations

import argparse
import copy
from pathlib import Path
from typing import Any

import yaml

from tripwire.policy.loader import load_policy
from tripwire.policy.schema import Policy

COMPONENTS = ("actions", "constraints", "limits", "sequences", "flows")


def _read(rule: dict[str, Any]) -> list[str]:
    """The arguments a tool rule reads, as checked_fields() counts them:
    its constraint keys and the field its budget sums."""
    names = list(rule.get("constraints") or {})
    summed = (rule.get("limits") or {}).get("sum_per_session")
    if summed and summed["field"] not in names:
        names.append(summed["field"])
    return names


def leave_one_out(policy: dict[str, Any], component: str) -> dict[str, Any]:
    """Return a deep copy of ``policy`` with one enforcement mechanism removed.

    allowed_args stays. An argument only the removed mechanism read was
    allowed without being listed, so it gets listed: removing a mechanism
    must never refuse a call the full policy lets through.
    """
    if component not in COMPONENTS:
        raise ValueError(f"unknown component {component!r}; choose from {', '.join(COMPONENTS)}")

    candidate = copy.deepcopy(policy)
    tools = candidate.get("tools", {})
    if component == "actions":
        candidate.setdefault("defaults", {})["unknown_tools"] = "allow"
        for rule in tools.values():
            rule["action"] = "allow"
    elif component in {"constraints", "limits"}:
        for rule in tools.values():
            read = _read(rule)
            rule.pop(component, None)
            listed = rule.get("allowed_args")
            if listed is not None:
                still_read = _read(rule)
                listed.extend([n for n in read if n not in still_read and n not in listed])
    else:
        candidate[component] = []

    # Fail during generation, not halfway through an expensive experiment.
    Policy.model_validate(candidate)
    return candidate


def generate(source: str | Path, destination: str | Path) -> list[Path]:
    source = Path(source)
    # the proxy's own loader, so a file it refuses (a key given twice, say)
    # is refused here too instead of being quietly deduplicated
    load_policy(source)
    raw = yaml.safe_load(source.read_text(encoding="utf-8"))

    destination = Path(destination)
    destination.mkdir(parents=True, exist_ok=True)
    written = []
    for component in COMPONENTS:
        path = destination / f"loo-no-{component}.yaml"
        header = (
            "# Generated by tripwire_gym.ablations.\n"
            f"# Full policy with only the {component} mechanism removed.\n"
        )
        path.write_text(
            header + yaml.safe_dump(leave_one_out(raw, component), sort_keys=False),
            encoding="utf-8",
        )
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="generate leave-one-component-out policies")
    parser.add_argument("--policy", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args(argv)
    for path in generate(args.policy, args.out):
        print(path)


if __name__ == "__main__":
    main()
