"""Generate leave-one-component-out policies from the policy under test.

Cumulative ablations answer whether a partial stack is sufficient.  They are
order-dependent.  These policies answer the cleaner publication question:
how much does the *full* stack change when exactly one mechanism is removed?
"""

from __future__ import annotations

import argparse
import copy
from pathlib import Path
from typing import Any

import yaml

from tripwire.policy.schema import Policy

COMPONENTS = ("actions", "constraints", "limits", "sequences", "flows")


def leave_one_out(policy: dict[str, Any], component: str) -> dict[str, Any]:
    """Return a deep copy of ``policy`` with one enforcement mechanism removed."""
    if component not in COMPONENTS:
        raise ValueError(f"unknown component {component!r}; choose from {', '.join(COMPONENTS)}")

    candidate = copy.deepcopy(policy)
    tools = candidate.get("tools", {})
    if component == "actions":
        candidate.setdefault("defaults", {})["unknown_tools"] = "allow"
        for rule in tools.values():
            rule["action"] = "allow"
    elif component in {"constraints", "limits"}:
        for rule in tools.values():
            rule.pop(component, None)
    else:
        candidate[component] = []

    # Fail during generation, not halfway through an expensive experiment.
    Policy.model_validate(candidate)
    return candidate


def generate(source: str | Path, destination: str | Path) -> list[Path]:
    source = Path(source)
    raw = yaml.safe_load(source.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise TypeError(f"{source}: expected a mapping")
    Policy.model_validate(raw)

    destination = Path(destination)
    destination.mkdir(parents=True, exist_ok=True)
    written = []
    for component in COMPONENTS:
        path = destination / f"loo-no-{component}.yaml"
        header = (
            "# Generated by tripwire_gym.ablations.\n"
            f"# Full policy with only the {component} mechanism removed.\n"
        )
        path.write_text(
            header + yaml.safe_dump(leave_one_out(raw, component), sort_keys=False),
            encoding="utf-8",
        )
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="generate leave-one-component-out policies")
    parser.add_argument("--policy", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args(argv)
    for path in generate(args.policy, args.out):
        print(path)


if __name__ == "__main__":
    main()
